export const DataList = [
    {
      id:1,
      nome:"Samambaia",
      img:require("../../assets/1.jpg"),
      precoAtual:10,
      precoReal:10,
      estrela:4.1,
      like:false
    },
    {
      id:2,
      nome:"Flore",
      img:require("../../assets/2.jpg"),
      precoAtual:10,
      precoReal:10,
      estrela:4.4,
      like:true
    },
    {
      id:3,
      nome:"Samambaia",
      img:require("../../assets/3.jpg"),
      precoAtual:10,
      precoReal:10,
      estrela:4.2,
      like:true
    },
    {
      id:4,
      nome:"Samambaia",
      img:require("../../assets/4.jpg"),
      precoAtual:10,
      precoReal:10,
      estrela:4.1,
      like:false
    },
    {
      id:5,
      nome:"Folha",
      img:require("../../assets/5.jpg"),
      precoAtual:10,
      precoReal:10,
      estrela:4.1,
      like:true
    },
    {
      id:6,
      nome:"Samambaia",
      img:require("../../assets/6.jpg"),
      precoAtual:10,
      precoReal:10,
      estrela:4.1,
      like:true
    },
    {
      id:7,
      nome:"Samambaia",
      img:require("../../assets/7.jpg"),
      precoAtual:10,
      precoReal:10,
      estrela:4.1,
      like:false
    },
    {
      id:8,
      nome:"Samambaia",
      img:require("../../assets/8.jpg"),
      precoAtual:10,
      precoReal:10,
      estrela:4.1,
      like:false
    },
  ]

